name: Python package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Pipenv
      run: |
        python -m pip install -U pip
        python -m pip install pipenv

    - name: Install dependencies
      run: python -m pipenv sync --dev

    - name: Lint with flake8
      run: python -m pipenv run lint

    - name: Test with pytest
      run: python -m pipenv run test
